Entername: Build 👑مترجم اسطوري اصدار 9👑

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: تحميل الملفات
        uses: actions/checkout@v4

      - name: تشغيل Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: تثبيت الحزم
        run: npm install

      - name: بناء EXE
        run: npx electron-builder --win --publish never

      - name: رفع البرنامج
        uses: actions/upload-artifact@v4
        with:
          name: 👑مترجم-اسطوري-اصدار-9👑
          path: dist/
